package answers;

/**
 * Created by seok on 2017. 11. 28..
 *
 * Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2.
 * The first ten pentagonal numbers are:
 * 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
 * It can be seen that P4 + P7 = 22 + 70 = 92 = P8.
 * However, their difference, 70 − 22 = 48, is not pentagonal.
 * Find the pair of pentagonal numbers, Pj and Pk,
 * for which their sum and difference are pentagonal
 * and D = |Pk − Pj| is minimised; what is the value of D?
 *
 */
public class Problem44 {
    public static void main(String args[]) {

        int result = 0;
        boolean notEnd = true;
        int i = 0;

        while ( notEnd ) {
            i++;
            int j = ( 3 * i * i - i ) / 2;

            for (int x = i - 1; x > 0; x--) {
                int m = ( 3 * x * x - x ) / 2;
                if (isPenta(j - m) && isPenta(j + m)) {
                    result = j - m;
                    notEnd = false;
                    break;
                }
            }

        }

        System.out.println(result);
    }

    private static boolean isPenta(int num) {
        double penTest = (Math.sqrt(1 + 24 * num) + 1.0) / 6.0;
        return penTest == ((int)penTest);
    }
}
