package answers;

/**
 * Created by seok on 2017. 11. 29..
 *
 * Triangle, pentagonal, and hexagonal numbers
 * are generated by the following formulae:
 * Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
 * Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
 * Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
 * It can be verified that T285 = P165 = H143 = 40755.
 * Find the next triangle number that is also pentagonal and hexagonal.
 *
 */
public class Problem45 {
    public static void main(String args[]) {

        long result = 0;
        boolean notEnd = true;
        long i = 143;

        while ( notEnd ) {
            i++;
            result = 2 * i * i - i;

            if ( isPenta(result) ) {
                notEnd = false;
            }
        }

        System.out.println(result);
    }

    private static boolean isPenta(long num) {
        double penTest = (Math.sqrt(1 + 24 * num) + 1.0) / 6.0;
        return penTest == ((int)penTest);
    }
}
